<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwingAdviser.Domain\SwingAdviser.Domain.csproj" />
    <ProjectReference Include="..\SwingAdviser.Infrastructure\SwingAdviser.Infrastructure.csproj" />
  </ItemGroup>

</Project>
