// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwingAdviser.Infrastructure.Persistence;

#nullable disable

namespace SwingAdviser.Infrastructure.Migrations
{
    [DbContext(typeof(SwingAdviserDbContext))]
    partial class SwingAdviserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SwingAdviser.Domain.Ai.AiEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ai_evaluation_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at_utc");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_code");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Verdict")
                        .HasColumnType("TEXT")
                        .HasColumnName("verdict");

                    b.Property<string>("_invalidationConditions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invalidation_conditions");

                    b.Property<string>("_positiveFactors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("positive_factors");

                    b.Property<string>("_riskFactors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_factors");

                    b.HasKey("Id")
                        .HasName("pk_ai_evaluations");

                    b.ToTable("ai_evaluations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Analysis.CandidateEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_evaluation_id");

                    b.Property<string>("Atr14")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("atr14");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("Ema100")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ema100");

                    b.Property<string>("Ema100TwentyDaysAgo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ema100_twenty_days_ago");

                    b.Property<string>("Ema20")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ema20");

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_date");

                    b.Property<int>("MacdCrossAgeDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("macd_cross_age_days");

                    b.Property<int>("MacdFreshnessScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("macd_freshness_score");

                    b.Property<string>("MacdHistogram")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_histogram");

                    b.Property<string>("MacdLine")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_line");

                    b.Property<int>("MacdMomentumScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("macd_momentum_score");

                    b.Property<int>("MacdPositionScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("macd_position_score");

                    b.Property<string>("MacdSignal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_signal");

                    b.Property<bool>("MarketRegimeAligned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("market_regime_aligned");

                    b.Property<int>("MarketRegimeScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("market_regime_score");

                    b.Property<string>("PreviousMacdHistogram")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_macd_histogram");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_code");

                    b.Property<string>("StrategyParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_parameters_json");

                    b.Property<int>("TrendStrengthScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trend_strength_score");

                    b.Property<string>("VolumeRatio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_ratio");

                    b.Property<int>("VolumeScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume_score");

                    b.HasKey("Id")
                        .HasName("pk_candidate_evaluations");

                    b.HasIndex("StockCode", "EvaluationDate", "Direction")
                        .HasDatabaseName("ix_candidate_evaluations_stock_code_evaluation_date_direction");

                    b.ToTable("candidate_evaluations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.MarketData.DailyBar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_bar_id");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<string>("High")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("high");

                    b.Property<string>("Low")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("low");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("open");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_code");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trade_date");

                    b.Property<long>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_daily_bars");

                    b.HasIndex("StockCode", "TradeDate")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_bars_stock_code_trade_date");

                    b.ToTable("daily_bars", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Execution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("execution_id");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("executed_at_utc");

                    b.Property<DateOnly?>("MarginDueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("margin_due_date");

                    b.Property<long>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("side");

                    b.Property<string>("SplitFactor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("split_factor");

                    b.Property<string>("_correctionLog")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("correction_log");

                    b.HasKey("Id")
                        .HasName("pk_executions");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_executions_position_id");

                    b.ToTable("executions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<string>("InitialAtr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_atr");

                    b.Property<bool>("IsMargin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_margin");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_code");

                    b.Property<string>("StopLossPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_loss_price");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Risk.HoldingEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("holding_evaluation_id");

                    b.Property<string>("AchievedRMultiple")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("achieved_r_multiple");

                    b.Property<string>("Atr14")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("atr14");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("close");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("decision");

                    b.Property<string>("Ema20")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ema20");

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_date");

                    b.Property<int>("HoldingBusinessDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("holding_business_days");

                    b.Property<string>("MacdLine")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_line");

                    b.Property<string>("MacdSignal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("macd_signal");

                    b.Property<long>("PositionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("StopLossPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stop_loss_price");

                    b.Property<string>("StrategyParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy_parameters_json");

                    b.HasKey("Id")
                        .HasName("pk_holding_evaluations");

                    b.HasIndex("PositionId", "EvaluationDate")
                        .HasDatabaseName("ix_holding_evaluations_position_id_evaluation_date");

                    b.ToTable("holding_evaluations", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Stocks.Stock", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("MarketSegment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("market_segment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("StockCode")
                        .HasName("pk_stocks");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Execution", b =>
                {
                    b.HasOne("SwingAdviser.Domain.Positions.Position", null)
                        .WithMany("Executions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_executions_positions_position_id");
                });

            modelBuilder.Entity("SwingAdviser.Domain.Positions.Position", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
